### ISSUE TITLE
Nested languages

### ISSUE THREAD

**Issue by d-Pixie** [slim-template/ruby-slim.tmbundle#21]
When using nested syntaxes, like javascript or markdown, the syntax highlighter is still action as if the code is slim. Here is an example:

![http://cl.ly/image/2h2Y1N1i0R3l](http://f.cl.ly/items/44382R2O0M0p0l2D0j0Y/Screen%20Shot%202012-12-04%20at%2014.55.30.png)

I had a look at the syntax definitions and can see that there are filters defined for all the nested languages. I did not find any references to them in the main syntax file however.

I know very little about how the syntax highlighter definitions work, but I'm willing to learn if you could point me to some resources on the subject and maybe mentor me occasionally. I'd be happy to fix this myself, if I could ;)

**Comment by tshedor** [comment]
@d-Pixie Been a while, but I believe the filters are now highlighting correctly. Please comment if you're still seeing this and I'll re-open.
