### ISSUE TITLE
Syntax Highlighting with filters and single quotes

### ISSUE THREAD

**Issue by thomasklemm** [slim-template/ruby-slim.tmbundle#23]
Hey, thanks for this great bundle! In SublimeText 2 I've gotten a small error in the highlighting probably occurring only with filters.

![image](https://f.cloud.github.com/assets/1100176/31141/e38a9f64-4f5f-11e2-98a7-aeb6ec00f8df.png)

Tested with the most recent version, freshly installed.

**Comment by tshedor** [comment]
Believe this has been fixed. Please comment if you can reproduce.
