### ISSUE TITLE
Unable to install on SublimeText 3 [Mac OS X] from package manager

### ISSUE THREAD

**Issue by mrThe** [slim-template/ruby-slim.tmbundle#34]
I'll tried to install it from package manager and nothing happened. (After restart nothing changed)

After it, i install it manually, and everything works, so maybe it problem with package manager.

**Comment by atteeela** [comment]
Thanks @jaredjenkins. It worked for me too with your instructions.

**Comment by tshedor** [comment]
It's been a while, and both the package manager and Sublime have seen many updates. I'm closing this for now, but please comment if this issue is reproducible.
