### ISSUE TITLE
Include in Readme Support for Chocolatapp

### ISSUE THREAD

**Issue by zephiro** [slim-template/ruby-slim.tmbundle#35]
It's not an official truffle, but I tried installing first git clone repo. In chocolatapp Actions > Install Extras -> Install from file => Bundle Work for me!!

**Comment by tshedor** [comment]
Hi @zephiro, PRs are welcome any time. If you do submit a PR, please note that using this bundle with Chocolatapp is an unofficial package and will not be explicitly supported by the maintainers of this repo.
