### ISSUE TITLE
Syntax highlight with rails helper

### ISSUE THREAD

**Issue by pywebdesign** [slim-template/ruby-slim.tmbundle#36]
Syntax highlight is horrible for this line and many rails tag helpers

= image_tag("logo.png", alt: "Cesure Logo", class: "logo")

alt: and class: are not the same color, parenthesis are another color ans : too.

It could be possible to catch the parenthesis, they are not necessary in ruby but could help syntax highlight. my 2 cents

**Comment by tshedor** [comment]
Hey @jaredbeck and @pywebdesign the Slim package was just updated with a fix to this. When convenient, would you please pull the update and verify that the helper is now highlighted as expected?

**Comment by jaredbeck** [comment]
I haven't used textmate or sublime in almost two years; can't help, sorry.
