### ISSUE TITLE
Tag attributes should be highlighted as ruby code

### ISSUE THREAD

**Issue by ktaragorn** [slim-template/ruby-slim.tmbundle#39]
Tag attributes in slim are basically treated as ruby code, as mentioned in https://github.com/slim-template/slim#ruby-attributes

This is not reflected in the highlighting however, as seen in this screenshot
![screenshot](https://cloud.githubusercontent.com/assets/2549496/3633850/b9cd274e-0eff-11e4-9fd7-32b1fe967243.png)

This leads to issues like https://github.com/slim-template/slim/issues/518 where I was doing something wrong, but it wasnt obvious because the highlighter didnt catch the fact that everything after `#` is commented out in ruby

**Comment by tshedor** [comment]
@ktaragorn it's been a while, but I believe this has been resolved by #62. Please comment here if you're able to reproduce.

**Comment by ktaragorn** [comment]
Looks good!
