### ISSUE TITLE
Multiline Ruby doesn't work

### ISSUE THREAD

**Issue by noinkling** [slim-template/ruby-slim.tmbundle#47]
When ending a line of Ruby with a `,` or `\`, the next line should continue to be in the Ruby scope (as per the Slim docs). Currently this does not work, the next line will reset to the standard Slim scope. Ruby strings can continue across lines properly however, so this must be possible.

I've had a look and made modifications but can't get this to work. One of my pull requests (#44) that got merged makes it so a Ruby line ending on `,` or `\` will continue it's scope to the end of that line, but it doesn't continue on the next line, it seems to just get overwritten by `entity.name.tag.slim`. I've tried messing with the regex for the beginning of that scope but had no luck.

**Comment by luckynumberslevin** [comment]
The problème is due to this commit https://github.com/slim-template/ruby-slim.tmbundle/commit/059dca5b6d1395c635700eee99e8e12fef153658 for the PR #44 

If you rollback this commit you will resolve our problem but the #41 reappear. For the moment I don't know how to solve it.

**Comment by halloffame** [comment]
+1 thanks @luckynumberslevin that helped

**Comment by tshedor** [comment]
@noinkling the Slim package was just updated with a fix to this, including the revert from @luckynumberslevin. When convenient, would you please pull the update and verify that multiline is highlighting as expected?

**Comment by noinkling** [comment]
Been a while since I opened this, but it seems to work fine now as far as I can tell :+1:
