### ISSUE TITLE
First line after `do` gets styled as ruby

### ISSUE THREAD

**Issue by halloffame** [slim-template/ruby-slim.tmbundle#53]
This relates to this issue https://github.com/slim-template/language-slim/issues/7

The first line after `do` is getting interpreted as ruby, not slim. I think this just started recently, I haven't noticed it before.

![screen shot 2015-01-29 at 11 21 26 am](https://cloud.githubusercontent.com/assets/957859/5964457/1a4dbfc4-a7a9-11e4-8466-2809b5bb2b66.png)

**Comment by flexbox** [comment]
Ahhh i have the same issue here.

**Comment by halloffame** [comment]
You can fix it temporarily by removing the `|\n` that was added on this line
https://github.com/slim-template/ruby-slim.tmbundle/pull/49/files#diff-c53c9767616c99387c87d68b79179e97L579

**Comment by skunkworker** [comment]
I ran into this same issue tonight.

**Comment by kreintjes** [comment]
Same problem over here

**Comment by mikemerritt** [comment]
This is still a problem and is quite annoying.

**Comment by tijn** [comment]
It totally is broken but I learned an easy way to avoid the issue.

It seems that `do` in slim is only needed when you want to use block arguments. If you don't, you may omit it. I think the code that handles the indentation implicitly puts the `do` back when it converts the template to code.

So the following snippet should be valid slim and also correctly highlighted in Sublime Text:

```slim
= content_for :header
  p the first line
  p the second line
```

**Comment by kreintjes** [comment]
Problem was fixed with https://github.com/slim-template/ruby-slim.tmbundle/pull/62, but seems to be back after updating to Sublime Text 3 to build 3126. @tshedor any chance you could take a look at this?

**Comment by tshedor** [comment]
@kreintjes I can confirm that the highlighting is broken again (using ST3 build 3126), but I'm going to hold off on debugging until ST3 is at the official release OR early November, whatever comes first. It seems like he's finally close to the official release, and I don't want to chase a bug that will eventually be patched. Are you able to get by with removing the `do`?

**Comment by kreintjes** [comment]
@tshedor Sure, no problem. Thanks for the reply!

**Comment by tshedor** [comment]
@kreintjes I'm going to use #72 as a reference for this instead since that's a clean issue
