### ISSUE TITLE
Error loading syntax file on Sublime 3

### ISSUE THREAD

**Issue by DamirSvrtan** [slim-template/ruby-slim.tmbundle#54]
I'm constantly getting an error when opening a slim file:

``` ruby
Error loading syntax file "Packages/Ruby Slim/Syntaxes/Ruby Slim.tmLanguage": boost::bad_any_cast: failed conversion using boost::any_cast
```

Any suggestions? Thnx

**Comment by jdsampayo** [comment]
I'm having the same issue from a long time ago, I uninstall the package and reinstall it time to time.

**Comment by tshedor** [comment]
@DamirSvrtan It's been a while, but are you still getting this error?

**Comment by DamirSvrtan** [comment]
@tshedor I'm not using sublime text 3 anymore so I'm not relevant to this issue.  Feel free to close it if others don't have this issue.
