### ISSUE TITLE
Feature Request: Classes and IDs should be different color than tags

### ISSUE THREAD

**Issue by kyleshevlin** [slim-template/ruby-slim.tmbundle#56]
You can use the longer Slim syntax (with parentheses) to get class and id highlighting, but I would love for it to highlight a different color naturally.

So something like: `p.intro` would have one color for the `p` tag and another color for the `.intro` class.

Is this possible?

**Comment by tshedor** [comment]
@kyleshevlin the latest Slim should have this highlighting. Would you mind updating and verifying?

**Comment by kyleshevlin** [comment]
Indeed they are different. Closing this issue.
