### ISSUE TITLE
ST crashes with certain characters at the beginning of a line.

### ISSUE THREAD

**Issue by bryanrite** [slim-template/ruby-slim.tmbundle#59]
I think the latest update breaks something in the parsing.

For example, I have a file `show.js.slim` that contains:

```slim
| 
  console.log("foo");
  console.log("bar");
```

This has previously opened fine in ST2 with RubySlim but this morning it would crash ST2. I realized that RubySlim had been updated. If I replace my local RubySlim package's `Syntaxes\Ruby Slim.tmLanguage` with the one from before 599768b4041cabc0afb1c43ced7dd22f821760ff was merged, everything works fine. The regex change in d16a9aa039f408ab46df4c969e72a39605845781 causes ST to crash when a line starts with a pipe `|` or a `$`.

**Comment by bryanrite** [comment]
It will also crash with a file like:

```slim
- if true
  | console.log("foo");
- else
  | console.log("bar");
```

So the character only has to begin the line to cause the crash.

**Comment by mangantyr** [comment]
also breaks on a single quote character.

**Comment by fredwu** [comment]
Are these caused by #57? If so I'll revert and ping the author. :)

**Comment by mangantyr** [comment]
yes, looks like maybe a missing $ sign at end of regex on line 228?

On Thu, Mar 31, 2016 at 6:55 PM, Fred Wu <notifications@github.com> wrote:

> Are these caused by #57
> <https://github.com/slim-template/ruby-slim.tmbundle/pull/57>? If so I'll
> revert and ping the author. :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/slim-template/ruby-slim.tmbundle/issues/59#issuecomment-204163556>
>



-- 

Mans Angantyr

Chief Digital Officer


[image: Wasabi Rabbit Logo] <http://www.wasabirabbit.com>
  [image: Twitter Logo] <https://twitter.com/wasabirabbit>   [image:
LinkedIn Logo] <http://www.linkedin.com/company/2228896>   [image: Facebook
Logo] <https://www.facebook.com/wasabirabbit>   [image: Tumblr Logo]
<http://vimeo.com/wasabirabbit>

*T*: 646 366 0000 <6463660000>   *M*: 646 491 1814 <0000000000>

19 Fulton Street, Suite 307
New York, NY 10038

**Comment by fredwu** [comment]
Hi @clthck, re the comments above would you be able to take a look at your recent changes? :)

**Comment by clthck** [comment]
I tried with the above code snippet and I don't have such issues.
FYI, I'm using ST3. I haven't tested on ST2. Anybody can try with ST2 one more time and confirm the issues?

**Comment by mangantyr** [comment]
this breaks on ST2.  testing is simple: 
1. open/create a .slim file.
2. place cursor at beginning of any line.
3. enter a pipe character.
4. watch editor crash

**Comment by solisoft** [comment]
It also crash on `$(function() {})` and press enter when the cursor is between {}

**Comment by clthck** [comment]
Why don't you just use ST3? Is there any specific reason for not upgrading? ST3 is still in beta phase, but it's almost stable. If you still need to stick to ST2, then we'd better revert the commit. I'm not planning to make it compatible with ST2 for now.

**Comment by solisoft** [comment]
maybe because I have a licence for ST2 and not ST3

**Comment by mangantyr** [comment]
are there any plans to either fix or reverting this commit?  it's not clear from this thread.
it's a bad bug,  which crashes the app, and is virtually impossible to avoid triggering.
everybody on our team has disabled the plugin as of last week.
but we love it, and would love install it again. 
thoughts?

**Comment by mocerinoj** [comment]
```-

**Comment by sbleon** [comment]
Please revert this fix. Thanks!

**Comment by fredwu** [comment]
Commit reverted.

**Comment by sbleon** [comment]
Thanks, @fredwu ! The package works again in ST2 after a Package Control: Upgrade Package.
