### ISSUE TITLE
March 28 release breaks Sublime Text 2

### ISSUE THREAD

**Issue by DannyBen** [slim-template/ruby-slim.tmbundle#60]
In the past several days, opening slim files just gets Sublime Text 2 to show nothing.

Some slim files open, but others wont.

1. [Here is an example of a file that causes the issue][1]
2. Using ruby slim version 2016.03.28.12.56.23
3. Using Sublime Text 2 version 2.0.2 build 2221 on Windows
4. Here is a screenshot of how Sublime 2 looks when I try to open it
![slim](https://cloud.githubusercontent.com/assets/2405099/14202007/34a0cd3e-f7fe-11e5-9b9f-0edb1f5ae773.png)

EDIT (and solutions for others):

1. I downloaded the ZIP file [from this commit][2] 
2. Removed all the Ruby Slim package files, leaving only the `package-metadata.json`
3. Placed the files from the ZIP file inside the old folder
4. Set Package Control to avoid auto upgrading Slim (Preferences > Package Settings > Package Control > User - and then add `"auto_upgrade_ignore": ["Ruby Slim"]`
5. Restart Sublime

[1]: https://dl.dropboxusercontent.com/u/5253945/github/show.html.slim?dl=1
[2]: https://github.com/slim-template/ruby-slim.tmbundle/tree/741ccd5620a73dfb35d0d199ab63ee28f63ed70b

**Comment by soykje** [comment]
Hi,

Same problem here, with SublimeText 2 on Ubuntu... Using the Package Controller, also, but same bug :( I had to remove the package, but any fix will be welcome !

**Comment by DannyBen** [comment]
@soykje there is a workaround in my original post.

**Comment by soykje** [comment]
@DannyBen Ttoo early for me, not enough coffee... didn't see your workaround :/. Waiting for the 'official' way also... ?

**Comment by DannyBen** [comment]
I am also waiting for an official fix - just saw you said "had to remove the package" so I thought I should point that out :smile:

**Comment by soykje** [comment]
Yep, thx a lot, I just applied your workaround, and it seems "back to normal" with it :+1:

**Comment by tshedor** [comment]
@DannyBen @soykje the latest Slim release includes a few patches (#62), and I tested it on ST2 OS X 10.9. When convenient, would you please update the package and see if Sublime is still crashing?

**Comment by DannyBen** [comment]
I can confirm that with **v2016.06.25.06.05.06**, the file linked in the original post is loading without a problem. I will of course keep using it, and report here if I see any failure.

Thanks for the fix.

**Comment by soykje** [comment]
Hi, I can confirm too, with ST2 on Ubuntu 16.04 :) Thanks for the fix!

**Comment by fredwu** [comment]
Great to hear, thanks @tshedor for the awesome work! 👏
