### ISSUE TITLE
[Feature request] Different scopes between correct and incorrect links.

### ISSUE THREAD

**Issue by Kristinita** [slim-template/ruby-slim.tmbundle#63]
For example, I have correct code:

```
div
    'Sasha Ruby,
    a href="https://www.instagram.com/nervov/" Sasha
    |  Diamond!
```

and incorrect code:

```
div
'Sasha Ruby,
    a href="https://www.instagram.com/nervov/" Sasha
    |  Diamond!
```

Highlight correct code on Codepen.io: [http://codepen.io/Kristinita/pen/qaBgaO](http://codepen.io/Kristinita/pen/qaBgaO)  
![](http://i.imgur.com/4pRZDH5.png)

Highlight incorrect code on Codepen.io: [http://codepen.io/Kristinita/pen/bwGzwv](http://codepen.io/Kristinita/pen/bwGzwv)  
![](http://i.imgur.com/wNj9t1L.png)

Highlighting are difference.

But in Ruby Slim syntax in Sublime Text scopes no difference for correct and incorrect code:
- _text.slim meta.tag entity.name.tag.slim_ — for tag `<a>`,
- _text.slim string.quoted.double.html meta.toc-list.id.html_ — for link.

I think it is necessary to make the distinction between scopes, so that users Slim saw errors in the code.

Thanks.

**Comment by tshedor** [comment]
@Kristinita Hope I resolved this in 1d54306. If not, please comment and let me know!
