### ISSUE TITLE
Opening a file crashes SB3 when using ruby-slim

### ISSUE THREAD

**Issue by Nerian** [slim-template/ruby-slim.tmbundle#65]
I am having a weird error:

Opening this file in Sublime Text with ruby-slim.tmbundle installed will crash SB3 every single time.

https://gist.github.com/Nerian/96fe28711bd36cf9e24f8b9fe22ce90e

I nuked the ~/Library/Application Support/Sublime Text 3  folder and only installed this package. And it crashed. It doesn't crash when I open the file without this package.

**Comment by yojimbosteel** [comment]
I'm having the same problem after update to ST 3124. Only one slim file currently causes crash so I suspect that it's a certain syntax causing the problem. Worked fine on ST 3114.

**Comment by Nerian** [comment]
As @yojimbosteel, it's only one file the one that causes the crash. There must be something wrong with some syntaxt

**Comment by Nerian** [comment]
I have pinpoint the offending code to this line:

javascript:
  default_currency_symbol = "#{ Money::Currency.find(current_space.default_currency).symbol }"

Opening a file with that line of code consistently causes a crash.

**Comment by yojimbosteel** [comment]
ST 3126 (released today) fixes the problem.

From ST:

> Build 3126
Release Date: 23 September 2016

    Added Indexing Status to the Help menu to give more information about what the indexer is doing
    Fixed a compatibility issue with some third party syntax definitions that include JavaScript.sublime-syntax
    Reduced the default number of worker processes used for indexing. This can be manually controlled via the index_workers setting
    API: Updated OpenSSL to 1.0.2i

**Comment by Nerian** [comment]
Sweet. Closing :)
