### ISSUE TITLE
First line of nested block not using correct syntax

### ISSUE THREAD

**Issue by elDub** [slim-template/ruby-slim.tmbundle#72]
```
= link_to('#') do |_|
  SPAN content
= link_to('#')
  SPAN content
= link_to('#') do
  SPAN content
```

![ruby slim](https://user-images.githubusercontent.com/1226748/28627218-28f9d464-71ef-11e7-956a-3df47a3aae95.png)

When a ruby `do` block is encountered _without_ a variable, the next line is not getting the correct syntax colorization applied.

This is using:
SublimeText Build 3126
Ruby Slim v2017.01.29.04.15.25

**Comment by tshedor** [comment]
Sorry, thought this would've been referenced here. d34daa8 resolves this.
