### ISSUE TITLE
Comments not being greyed out.

### ISSUE THREAD

**Issue by unmultimedio** [slim-template/ruby-slim.tmbundle#74]
When comments are indented at same level, without a space from last line of code, it doesn't gets greyed out if slim has ruby code.

![slim-comment](https://user-images.githubusercontent.com/4431392/29905756-237954da-8dd6-11e7-94de-4ac5159f3723.gif)

**Comment by tshedor** [comment]
@unmultimedio Are you still seeing this with the release of ST3? I've tried to duplicate in 3143 and it's highlighting properly

**Comment by unmultimedio** [comment]
Actually @tshedor I'm using Atom. Theres this repo who uses this to generate automatically a language package from this build: https://github.com/IanMitchell/slim-language

**Comment by kartikluke** [comment]
![screen shot 2017-09-16 at 3 07 25 pm](https://user-images.githubusercontent.com/3857139/30511144-5d6b9654-9af0-11e7-8aae-0f738f2bbf50.png)

Getting this after upgrading to the latest Sublime build. If I use a slash inside Ruby it messes up the commenting.

**Comment by tshedor** [comment]
@unmultimedio Ah, I see. I can't speak to how they're compiling this repo, and the README/referenced issue says it's being compiled from [a different fork](https://github.com/tycooon/slim-tmbundle). I'm going to consider this closed here but leave it open the issue you opened on the official Atom package - slim-template/language-slim#26. I plan to jump into that code soon.

**Comment by tshedor** [comment]
@kartikluke This is actually parsing correctly in Slim but not in the Ruby syntax definition that Sublime comes with. sublimehq/Packages#1142 resolves this (I pulled and tried it out locally) and we'll probably see it in the next release.

**Comment by kartikluke** [comment]
@tshedor How do I load it from the Github repo? Releases take ages.

**Comment by tshedor** [comment]
@kartikluke 
1) Install the [PackageResourceViewer](https://github.com/skuroda/PackageResourceViewer) package
2) From the Command Palette, choose "PackageResourceViewer: Open Resource" 
3) Choose Ruby
4) Choose Ruby.sublime-syntax
5) Replace your local Ruby.sublime-syntax with the contents of [the origin file](https://github.com/sublimehq/Packages/blob/master/Ruby/Ruby.sublime-syntax)

That will update Ruby highlighting immediately, no compiling required.

**Comment by kartikluke** [comment]
@tshedor Thanks man.
