### ISSUE TITLE
Text block started with a tag

### ISSUE THREAD

**Issue by printercu** [slim-template/ruby-slim.tmbundle#75]
Hi! Thanks for maintaining this bundle!

If text block starts on the tag definition line, all 1st words on next lines are highlighted as tags:

![image](https://user-images.githubusercontent.com/1144890/30636414-10149138-9dfe-11e7-9377-c88619caed30.png)

Can this be fixed?

**Comment by tshedor** [comment]
Hey @printercu  - I poked around, and it might be a while for this one. The trick is distinguishing when a tag is actually just plain text versus when it's a continuation of the tag...and I'm scratching my head on where to start with that. I'll let you know.

**Comment by deathaxe** [comment]
This issue is fixed in Slim 2.0.

Slim 2.0 for ST4 has been released at Package Control, with source moved to https://github.com/SublimeText/Slim.

![grafik](https://user-images.githubusercontent.com/16542113/212364520-3b61de61-8b86-4d88-ab84-548a19c80e18.png)
