### ISSUE TITLE
Error with syntax highlight

### ISSUE THREAD

**Issue by MaxDBN** [slim-template/ruby-slim.tmbundle#78]
After the recent update, on every slim file I open I get the following error:

> Error loading syntax file "Packages/Ruby Slim/Syntaxes/Ruby Slim.tmLanguage": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

And the syntax highlight is not working because of it

**Update:** I rolled back to version 3143 of Sublime for this to work again

**Comment by MettaAudio** [comment]
I had this same issue, and after some further reading discovered [this thread](https://github.com/jonschlinkert/sublime-markdown-extended/issues/141). I don't know how this is related, but _disabling_ the "Markdown" package fixed the issue for me. In some cases in this thread the solution was to enable Markdown, so YMMV.
